# Generated by Django 5.2 on 2025-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('muallif', models.CharField(max_length=100)),
                ('yaratilgan_yil', models.PositiveIntegerField()),
                ('til', models.CharField(max_length=30)),
                ('janr', models.CharField(max_length=100)),
                ('betlar_soni', models.IntegerField()),
                ('qisqacha_mazmuni', models.TextField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
